# The following enables several GHC versions to be tested; often it's enough to
# test only against the last release in a major GHC version. Feel free to omit
# lines listings versions you don't need/want testing for.
language: haskell

ghc:
  - "7.6.3"
  - "7.8.4"
  - "7.10.3"
  - "8.0.2"
  - "8.2.2"
  - "8.4.4" 
  - "8.6.5"
  - "8.8.4"

before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install libgsl0-dev liblapack-dev libblas-dev libxrandr-dev
